.Dd $Mdocdate$
.Dt LCHAT 1
.Os
.Sh NAME
.Nm lchat
.Nd line chat
.Sh SYNOPSIS
.Nm
.Op Fl eh
.Op Fl n Ar lines
.Op Fl p Ar prompt
.Op Fl t Ar title
.Op Fl i Ar in
.Op Fl o Ar out
.Op directory
.Sh DESCRIPTION
The
.Nm
utility is a command line front end for ii-like chat programs.
It uses
.Xr tail
in the background to get output lines from
.Ar out .

The options are as follows:
.Bl -tag -width Ds
.It Fl e
Allow to enter empty lines.
.It Fl h
Shows usage text.
.It Fl n Ar lines
Shows
.Ar lines
of chat history at startup.
.It Fl p Ar prompt
Use
.Ar prompt
as prompt for the input line.
.It Fl t Ar title
Use
.Ar title
as title terminal window.
In a
.Xr tmux 1
or
.Xr screen 1
environment its change the window name instead of the window title.
.It Fl i Ar in
Use path of
.Ar in
as in-file.
Default is 'in'.
This overides
.Ar directory .
.It Fl o Ar out
Use path of
.Ar out
as out-file.
Default is 'out'.
This overides
.Ar directory .
.It Ar directory
Uses
.Ar directory
to search for in and out file.
Default directory path is '.'.
.El
.Sh SEE ALSO
.Xr tail 1 ,
.Xr ii 1
.Sh AUTHORS
.Nm
was written by Jan Klemkow.
